# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

include ./nord-kitty/nord.conf

font_family      Inconsolata
font_size 18.0

scrollback_lines 4000
wheel_scroll_multiplier 5.0
wheel_scroll_multiplier 5.0

mouse_hide_wait 2.0

enable_audio_bell yes
window_alert_on_bell yes

# Disable kitty's unicode widget. It gets triggered by the QMK keyboard send_unicode strings and blocks the terminal.
# Unfortunately it seems to lack support for IBUS Unicode so it only adds garbage but at least it does not lock.
map ctrl+shift+u no_op

confirm_os_window_close 0
