# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Add a newline between prompts.
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '[➜](bold green)'

[cpp]
disabled = false

[directory]
truncation_length = 8
truncation_symbol = '…/'

[sudo]
disabled = false
